services:
  nginx:
    image: openresty/openresty:1.25.3.2-2-alpine-apk
    ports:
      - "8888:8888"
    volumes:
      - ./cache:/var/cache/nginx
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
  nodejs:
    build: .
    ports:
      - "8081:8081"
