on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: read
  packages: write
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: npm install
        run: npm ci
      - name: npm build
        run: npm run build
      - name: Generate Docker Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        if: ${{ !env.ACT }}
        with:
          images: ghcr.io/bdalpe/tf-provider-mirror
          tags: |
            type=ref,event=tag
            type=raw,value=latest
          flavor: |
            latest=false
      - name: Build Docker Container Image
        uses: docker/build-push-action@v6
        with:
          push: ${{ !env.ACT }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
